#公会配置文件

#默认创建公会金额
createSocietyMoney: 100000.0

#是否开启公会称号显示
isChat: true
#称号格式
chatText: "§l§6[§a世界§c♠§6${world}][§cLv_§9${societyGrade}§c♥§a公会§4♚§6${societyName}§5✔§e职位§c►§d${post}§6]§b${playerName}§f➣ ${message}"

#是否显示底部信息 （如果有底部显示建议false）
isTip: false
#底部显示格式 (新手腐竹勿动)
tipText: "\n\n§c§l物品ID§f>> §5{itemID}    §a世界§f>> §5${world}   §b金币§f>> §5${money}
          \n§b公会§f>> §5${societyName} §6职位§f>> §5${post} §cTPS§f>> §5${tps}"

#此配置信息暂时勿动!
post:
  - {
    name: 会长, #名称
    grade: 4, #职位等级
    count: 1 #可拥有数量 (会长必须唯一) -1代表无限
  }
  - {
    name: 副会长,
    grade: 3,
    count: 1
  }
  - {
    name: 元老,
    grade: 2,
    count: 2
  }
  - {
    name: 小队长,
    grade: 1,
    count: 1
  }
  - {
    name: 玩家,
    grade: 0,
    count: -1
  }

#公会等级(人数人数控制后期增加)
#配置格式如下 公会等级: [最大成员数量,升级所需要的金额]
#此配置暂时请勿改动,1.0.0没有此功能
grade1:
  - 10
  - 1000
grade2:
  - 20
  - 10000
grade3:
  - 30
  - 20000
grade4:
  - 40
  - 40000
grade5:
  - 50
  - 80000
grade6:
  - 60
  - 100000
grade7:
  - 70
  - 1000000

